### ISSUE TITLE
Edge docs generation seems to be broken

### ISSUE THREAD

**Issue by fxn** [rails/rails-docs-server#20]
Hey!

Looks like edge docs generation is broken:

```
Generating API format into /home/rails/master/doc/rdoc...
[2019-03-22 04:16:13 UTC] ALL="1" rvm 2.5.3 do bundle _1.16.1_ exec rake guides:generate:html >/dev/null
/home/rails/.rvm/rubies/ruby-2.5.3/bin/ruby rails_guides.rb
/home/rails/master/actionview/lib/action_view/lookup_context.rb:289:in `formats=': Invalid formats: "html" (ArgumentError)
        from /home/rails/master/actionview/lib/action_view/renderer/abstract_renderer.rb:97:in `prepend_formats'
        from /home/rails/master/actionview/lib/action_view/renderer/template_renderer.rb:11:in `render'
        from /home/rails/master/actionview/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
        from /home/rails/master/actionview/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
        from /home/rails/master/actionview/lib/action_view/renderer/renderer.rb:22:in `render'
        from /home/rails/master/actionview/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
        from /home/rails/master/actionview/lib/action_view/base.rb:304:in `in_rendering_context'
        from /home/rails/master/actionview/lib/action_view/helpers/rendering_helper.rb:30:in `render'
        from /home/rails/master/guides/rails_guides/generator.rb:167:in `generate_guide'
        from /home/rails/master/guides/rails_guides/generator.rb:94:in `block in generate_guides'
        from /home/rails/master/guides/rails_guides/generator.rb:92:in `each'
        from /home/rails/master/guides/rails_guides/generator.rb:92:in `generate_guides'
        from /home/rails/master/guides/rails_guides/generator.rb:40:in `generate'
        from rails_guides.rb:30:in `<main>'
rake aborted!
```

Probably nothing to do with the recent activity by @localhostdotdev, but let me do a mention just in case.

(Please remember that anything merged to `master` goes automatically to production.)

**Comment by rafaelfranca** [comment]
This is a bug in the code on Rails. We have an issue there. https://github.com/rails/rails/issues/35697

**Comment by rafaelfranca** [comment]
It should be fixed now.
